"""Call graph and function summaries (architecture §19, §20)."""

from coretrace_python.interprocedural.callgraph import (
    Arguments,
    CallGraph,
    CallGraphAnalysis,
    CallSite,
    ExternalSymbol,
    KnownFunction,
    ModuleFunction,
    SymbolRead,
    Target,
    UnknownTarget,
)
from coretrace_python.interprocedural.modulegraph import (
    ModuleGraph,
    build_module_graph,
    discover_files,
    discover_sources,
    project_symbol,
)
from coretrace_python.interprocedural.summaries import (
    FILTER_ARGUMENTS,
    Cleared,
    Clearing,
    ClearingAnalysis,
    ExternalCall,
    FunctionSummary,
    Mutation,
    NonlocalWrite,
    ProjectSummaries,
    SummaryAnalysis,
    SummaryIndex,
    SummaryTable,
    TemplateCalls,
    TemplateCallsAnalysis,
    TemplateFilter,
    cleared_by,
)

__all__ = [
    "FILTER_ARGUMENTS",
    "Arguments",
    "CallGraph",
    "CallGraphAnalysis",
    "CallSite",
    "Cleared",
    "Clearing",
    "ClearingAnalysis",
    "ExternalCall",
    "ExternalSymbol",
    "FunctionSummary",
    "KnownFunction",
    "ModuleFunction",
    "ModuleGraph",
    "Mutation",
    "NonlocalWrite",
    "ProjectSummaries",
    "SummaryAnalysis",
    "SummaryIndex",
    "SummaryTable",
    "SymbolRead",
    "Target",
    "TemplateCalls",
    "TemplateCallsAnalysis",
    "TemplateFilter",
    "UnknownTarget",
    "build_module_graph",
    "cleared_by",
    "discover_files",
    "discover_sources",
    "project_symbol",
]
