"""Security models and the global multi-kind taint engine (architecture §16, §17)."""

from coretrace_python.taint.engine import (
    Taint,
    TaintAnalysis,
    TaintFacts,
    TaintFlow,
    propagate_taint,
)
from coretrace_python.taint.models import (
    AuthorizationGuard,
    EntryPoint,
    Model,
    ModelError,
    ModelTable,
    NamedParameter,
    RouteRegistrar,
    Sanitizer,
    SecurityModelAnalysis,
    SecurityModelRegistry,
    Sink,
    Source,
    SuffixSink,
    TaintKind,
    TypedParameter,
    Validator,
)
from coretrace_python.taint.routes import RegisteredRoutes, Routes, registered_routes

__all__ = [
    "AuthorizationGuard",
    "EntryPoint",
    "Model",
    "ModelError",
    "ModelTable",
    "NamedParameter",
    "RegisteredRoutes",
    "RouteRegistrar",
    "Routes",
    "Sanitizer",
    "SecurityModelAnalysis",
    "SecurityModelRegistry",
    "Sink",
    "Source",
    "SuffixSink",
    "Taint",
    "TaintAnalysis",
    "TaintFacts",
    "TaintFlow",
    "TaintKind",
    "TypedParameter",
    "Validator",
    "propagate_taint",
    "registered_routes",
]
